logging:
  file:
    name:
  level:
    root: INFO
    com.openresearch: DEBUG
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15.15t]){faint} %clr(%F:%L){cyan} %clr(:){faint} %m %clr({){faint}%X%clr(}){faint}%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}

spring:
  application:
    name: spring-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5532}/${POSTGRES_DB:springapi}
    username: ${POSTGRES_USER:springapi}
    password: ${POSTGRES_PASSWORD:springapi}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 3300000
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
  jackson:
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_INVALID_SUBTYPE: false
    serialization:
      INDENT_OUTPUT: true
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: true
      WRITE_ENUMS_USING_TO_STRING: true
      WRITE_NULL_MAP_VALUES: true
      WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED: false
      FAIL_ON_SELF_REFERENCES: true
    default-property-inclusion: always
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        generate_statistics: false
    show-sql: false
