openapi: 3.0.3
info:
  title: spring-api
  version: v1
servers:
  - url: https://localhost:8080
paths:
  /api/v1/example:
    post:
      summary: create new entry
      description: Method to create a new example.
      operationId: createExample
      tags:
        - example
      parameters:
        - $ref: "#/components/parameters/apiKeyRequired"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExampleNew"
      security:
        - ApiKeyAuth: []
      responses:
        "201":
          description: "Response object"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Example"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: get all examples
      description: Method to get a list of all examples.
      operationId: readExamples
      tags:
        - example
      parameters:
        - $ref: "#/components/parameters/apiKeyRequired"
      security:
        - ApiKeyAuth: [ ]
      responses:
        "200":
          description: "Response object"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExampleList"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  parameters:
    apiKeyRequired:
      in: "header"
      name: "X-API-Key"
      description: "uuid key of the tenant"
      required: true
      schema:
        type: "string"
        format: "uuid"
  schemas:
    ExampleNew:
      description: DTO for creating a new example.
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 254
    Example:
      description: DTO with all fields.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 254
        lock_version:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ExampleList:
      description: Listing of examples.
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Example'
    ErrorArgument:
      description: Arguments used in the error message.
      properties:
        key:
          type: "string"
        value:
          type: "string"
        type:
          type: "string"
      required:
        - "key"
        - "type"
    Error:
      description: Custom error object with translated messages.
      properties:
        time:
          type: "string"
          format: "date-time"
        code:
          type: "string"
        title:
          type: "string"
        message:
          type: "string"
        args:
          type: "array"
          items:
            $ref: "#/components/schemas/ErrorArgument"
      required:
        - "time"
        - "code"
        - "title"
        - "message"
